"""Initial schema

Revision ID: f92a377d34f9
Revises: 
Create Date: 2026-09-06 02:33:49.981998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92a377d34f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'route', name='uq_idempotency_key_route')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPS_AGENT', 'PASSENGER', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aircraft_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DELAYED', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flight_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number', 'origin', 'destination', name='uq_flight_number_origin_dest')
    )
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='itinerary_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_legs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('leg_order', sa.Integer(), nullable=False),
    sa.Column('seat_class', sa.Enum('FIRST', 'BUSINESS', 'ECONOMY', name='seat_class'), nullable=False),
    sa.Column('fare_type', sa.Enum('BASIC', 'FLEXIBLE', name='fare_type'), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('old_departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_origin', sa.String(length=3), nullable=False),
    sa.Column('new_origin', sa.String(length=3), nullable=False),
    sa.Column('old_destination', sa.String(length=3), nullable=False),
    sa.Column('new_destination', sa.String(length=3), nullable=False),
    sa.Column('rebooking_rule', sa.Enum('AUTO_REBOOK', 'NOTIFY_ONLY', 'NONE', name='rebooking_rule'), nullable=False),
    sa.Column('fare_policy_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('affected_bookings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_class', sa.Enum('FIRST', 'BUSINESS', 'ECONOMY', name='seat_class'), nullable=False),
    sa.Column('fare_type', sa.Enum('BASIC', 'FLEXIBLE', name='fare_type'), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('HELD', 'EXPIRED', 'CONFIRMED', 'RELEASED', name='hold_status'), nullable=False),
    sa.Column('hold_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_class', sa.Enum('FIRST', 'BUSINESS', 'ECONOMY', name='seat_class'), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('held_seats', sa.Integer(), nullable=False),
    sa.Column('overbooking_policy', sa.Enum('HARD_NEVER_OVERSELL', 'BUFFER_ALLOWED', name='overbooking_policy'), nullable=False),
    sa.Column('overbooking_buffer', sa.Integer(), nullable=False),
    sa.Column('fare_basic', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fare_flexible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booking_cutoff_hours', sa.Integer(), nullable=False),
    sa.Column('group_booking_policy', sa.Enum('FULL_FAIL', 'PARTIAL_HOLD', 'WAITLIST', name='group_booking_policy'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'seat_class', name='uq_seatinv_flight_class')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_class', sa.Enum('FIRST', 'BUSINESS', 'ECONOMY', name='seat_class'), nullable=False),
    sa.Column('passenger_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('loyalty_tier', sa.Enum('NONE', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='loyalty_tier'), nullable=False),
    sa.Column('fare_type', sa.Enum('BASIC', 'FLEXIBLE', name='fare_type'), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PROMOTED', 'EXPIRED', 'CANCELLED', name='waitlist_status'), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('loyalty_rank', sa.Integer(), nullable=False),
    sa.Column('fare_type_rank', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_class', sa.Enum('FIRST', 'BUSINESS', 'ECONOMY', name='seat_class'), nullable=False),
    sa.Column('fare_type', sa.Enum('BASIC', 'FLEXIBLE', name='fare_type'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'REBOOKING_PENDING', name='booking_status'), nullable=False),
    sa.Column('cancellation_policy', sa.Enum('REFUNDABLE', 'CREDIT_ONLY', 'NON_REFUNDABLE', name='cancellation_policy'), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=True),
    sa.Column('itinerary_id', sa.UUID(), nullable=True),
    sa.Column('airline_initiated', sa.Boolean(), nullable=False),
    sa.Column('flight_cancellation_outcome', sa.Enum('REFUND', 'REBOOK', 'TRAVEL_CREDIT', name='flight_cancellation_outcome'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['hold_id'], ['seat_holds.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_table('passengers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='passenger_status'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=5), nullable=False),
    sa.Column('seat_class', sa.Enum('FIRST', 'BUSINESS', 'ECONOMY', name='seat_class'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('hold_id', sa.UUID(), nullable=True),
    sa.Column('passenger_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hold_id'], ['seat_holds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=True),
    sa.Column('refund_type', sa.Enum('CASH', 'TRAVEL_CREDIT', 'NONE', name='refund_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='refund_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.drop_table('physical_seats')
    op.drop_table('travel_credits')
    op.drop_table('passengers')
    op.drop_table('bookings')
    op.drop_table('waitlist_entries')
    op.drop_table('seat_inventory')
    op.drop_table('seat_holds')
    op.drop_table('schedule_changes')
    op.drop_table('itinerary_legs')
    op.drop_table('itineraries')
    op.drop_table('flights')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
