#!/bin/bash
# =============================================================================
# scripts/setup-n8n-credentials.sh
# =============================================================================
# n8n Credential Setup Guide for Flight Management System
# Run this AFTER importing n8n-production.json into your n8n instance
# =============================================================================

set -e

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     SkyFlow FMS — n8n Credential Setup Guide                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This script guides you through setting up the 5 required credentials."
echo "All credentials are entered via the n8n UI — this script just shows you what to do."
echo ""

# ─── Step 1: Supabase Postgres ──────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 1️⃣  SUPABASE POSTGRES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Where to get: Supabase Dashboard → Your Project → Settings → Database"
echo ""
echo "  In n8n:"
echo "  ─ Go to: Credentials → Add Credential → Postgres"
echo "  ─ Name it EXACTLY: 'Postgres account'"
echo "  ─ Fill in:"
echo ""
echo "  Host:      db.<YOUR-PROJECT-REF>.supabase.co"
echo "  Database:  postgres"
echo "  User:      postgres"
echo "  Password:  <YOUR-DB-PASSWORD>"
echo "  Port:      5432  (or 6543 for pooler)"
echo "  SSL:       ✅ Enable (Required for Supabase)"
echo ""

# ─── Step 2: Gmail OAuth2 ───────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 2️⃣  GMAIL OAUTH2"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Where to get: console.cloud.google.com → APIs & Services → Credentials"
echo "  (Or use n8n's built-in Gmail OAuth — easiest option)"
echo ""
echo "  In n8n:"
echo "  ─ Go to: Credentials → Add Credential → Gmail OAuth2"
echo "  ─ Name it EXACTLY: 'Gmail account'"
echo "  ─ Click 'Connect my account' and authorize with your Google account"
echo ""
echo "  ⚠️  Make sure Gmail API is enabled in Google Cloud Console"
echo ""

# ─── Step 3: Google Gemini ──────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 3️⃣  GOOGLE GEMINI (PaLM) API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Where to get: aistudio.google.com → Get API Key"
echo ""
echo "  In n8n:"
echo "  ─ Go to: Credentials → Add Credential → Google PaLM/Gemini API"
echo "  ─ Name it EXACTLY: 'Google Gemini(PaLM) Api account'"
echo "  ─ Paste your API Key"
echo ""

# ─── Step 4: Groq API ───────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 4️⃣  GROQ API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Where to get: console.groq.com → API Keys → Create API Key"
echo ""
echo "  In n8n:"
echo "  ─ Go to: Credentials → Add Credential → Groq API"
echo "  ─ Name it EXACTLY: 'Groq account'"
echo "  ─ Paste your API Key"
echo ""

# ─── Step 5: Pinecone ───────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 5️⃣  PINECONE API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Where to get: app.pinecone.io → API Keys"
echo ""
echo "  In n8n:"
echo "  ─ Go to: Credentials → Add Credential → Pinecone API"
echo "  ─ Name it EXACTLY: 'Pinecone account'"
echo "  ─ Paste your API Key"
echo ""
echo "  ⚠️  Also create Pinecone index named 'hackathon' with:"
echo "      Dimensions: 768 (Gemini text-embedding-004)"
echo "      Metric: cosine"
echo "      Namespace: airline-policies"
echo ""

# ─── Step 6: Environment Variables ──────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 6️⃣  ENVIRONMENT VARIABLES (in n8n)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  In n8n → Settings → Environment Variables:"
echo ""
echo "  OPERATIONS_EMAIL = your-admin@gmail.com"
echo "  FMS_BACKEND_URL  = https://hackathon-production-4daa.up.railway.app"
echo ""

# ─── Final Steps ────────────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ✅  FINAL STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Import n8n-production.json → n8n → Workflows → Import from file"
echo "  2. Map each credential in the workflow to the credentials you created"
echo "  3. Test each sub-workflow manually by clicking 'Test workflow'"
echo "  4. Activate the workflow (toggle at top-right)"
echo "  5. Check the 'Executions' tab to confirm everything runs"
echo ""
echo "  Test order:"
echo "  ─ Check-in reminder (manually set a booking departure to NOW + 24h)"
echo "  ─ Waitlist promotion (join waitlist on full flight, then trigger)"
echo "  ─ Refund escalation (create PENDING refund older than 3 days)"
echo "  ─ Policy ingestion (paste policy text, click manual trigger)"
echo "  ─ RAG support (send email to the connected Gmail inbox)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Setup complete! Your n8n automation is ready. 🚀"
echo "═══════════════════════════════════════════════════════════════"
echo ""
